version: '3'

services:

  nest:
    build: ./backend/nestjs/
    container_name: nest
    ports: 
      - "3000:3000"
    volumes:
      - ./backend/nestjs/source/:/usr/src/app/
    depends_on:
      - postgresql
    restart: always
    networks:
      backend:
        ipv4_address: 172.19.0.2

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    restart: always
    networks:
      backend:
        ipv4_address: 172.19.0.3

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    networks:
      backend:
        ipv4_address: 172.19.0.4
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 127.19.0.0/16
         gateway: 127.19.0.1

