version: '3'

services:

  nest:
    build: ./backend/
    container_name: nest
    ports: 
      - "3000:3000"
    volumes:
      - ./backend/source/:/usr/src/app/
    depends_on:
      - postgresql
    restart: always
    networks:
      back:
        ipv4_address: 10.1.0.2

  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
    restart: always
    networks:
      back:
        ipv4_address: 10.1.0.3

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    restart: always
    networks:
      back:
        ipv4_address: 10.1.0.4
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  react:
    container_name: react
    build: ./frontend/
    restart: always
    ports: 
      - "3002:3002"
    volumes:
      - ./frontend/my-app/:/usr/src/app/

networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

